### ISSUE TITLE
Issues with the current code

### ISSUE THREAD

**Issue by PedanticHacker** [PedanticHacker/ChessFighter#4]
- [x] The `scroll_up()` and `scroll_down()` slots in `window.py` should display `previous` and `next` chessboard position on a mouse wheel scroll, respectively. If the scroll of the wheel is made upwards, the `scroll_up()` slot should display the previous chessboard position. This should be indicated in the moves table by having that move item selected as well. The opposite should happen for scrolling the wheel downwards.

Implement this functionality.
***
- [x] While a historic chessboard position is being displayed and a new move is added, Chess Fighter crashes:
```
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1486, in _parse_uci_bestmove
    move = board.push_uci(tokens[0].lower())
  File "C:\Program Files\Python38\lib\site-packages\chess\__init__.py", line 2896, in push_uci
    move = self.parse_uci(uci)
  File "C:\Program Files\Python38\lib\site-packages\chess\__init__.py", line 2883, in parse_uci
    raise ValueError(f"illegal uci: {uci!r} in {self.fen()}")
ValueError: illegal uci: 'c5d4' in rnbqkbnr/pp2pppp/3p4/8/3QP3/5N2/PPP2PPP/RNB1KB1R b KQkq - 0 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Boštjan\Desktop\Chess Fighter\source\window.py", line 675, in invoke
    result = self.engine.play(
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 2386, in play
    return future.result()
  File "C:\Program Files\Python38\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Program Files\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Program Files\Python38\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1316, in play
    return await self.communicate(UciPlayCommand)
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 768, in communicate
    return await command.result
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 979, in _line_received
    self.line_received(engine, line)
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1273, in line_received
    self._bestmove(engine, line.split(" ", 1)[1])
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1292, in _bestmove
    best = _parse_uci_bestmove(engine.board, arg)
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1488, in _parse_uci_bestmove
    raise EngineError(err)
chess.engine.EngineError: illegal uci: 'c5d4' in rnbqkbnr/pp2pppp/3p4/8/3QP3/5N2/PPP2PPP/RNB1KB1R b KQkq - 0 4
[Finished in 25.3s with exit code 3221226505]
[shell_cmd: python -u "C:\Users\Boštjan\Desktop\Chess Fighter\run.py"]
[dir: C:\Users\Boštjan\Desktop\Chess Fighter]
[path: C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\]
```
Fix this `ValueError`. I think a debugger is needed to see what exactly is going on. I tried Python's `PDB debugger`, but I get an infinite recursion if a `breakpoint()` is set in `PyQt5's main event loop`.

**Comment by mfitzp** [comment]
Hey @PedanticHacker  I've pushed the addition to handle the scrolling on the board, which now works (see PR https://github.com/PedanticHacker/ChessFighter/pull/5).

For 2 I can't reproduce that error -- unfortunately, not because it works, but because I get another.

Whenever I change a historic move then continue to play, at some point afterwards I'll see the following kind of error complaining about an illegal move?

```
U:\home\martin\repos\code-review\ChessFighter>python run.py
Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python37\lib\site-packages\chess\engine.py", line 1486, in _parse_uci_bestmove
    move = board.push_uci(tokens[0].lower())
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python37\lib\site-packages\chess\__init__.py", line 2896, in push_uci
    move = self.parse_uci(uci)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python37\lib\site-packages\chess\__init__.py", line 2883, in parse_uci
    raise ValueError(f"illegal uci: {uci!r} in {self.fen()}")
ValueError: illegal uci: 'd8a5' in rnb1kb1r/pp3ppp/4pn2/qNpp2B1/3P4/8/PPPQPPPP/R3KBNR b KQkq - 3 6
```

My assumption is that the engine hasn't been updated properly with the new positions?

For the error your seeing, it's a bit strange since the pop is erroring on `self.history.pop()` when there is another `pop` immediately before it, e.g.

```
        moves_to_pop = len(self.history) - self.current_move_index
        self.san_moves.pop(moves_to_pop)
        self.history.pop(moves_to_pop)
        self.board.move_stack.pop(moves_to_pop)
```

The question is, how are the history and san_moves list lengths different?

**Comment by PedanticHacker** [comment]
Well, I had to add another array (a Python list) to store the moves in SAN (Standard Algebraic Notation) format and then feed that data to the table model to get the moves displayed in the table view in this format. The necessary thing here is that the conversion from LAN (Long Algebraic Notation) to SAN (Standard Algebraic Notation) must be made before a move is pushed, otherwise the program crashes, because the state of the board changes, and for python-chess the san() function of chess.Board() checks whether the move is legal in the context of the current board state.

How the arrays `history` and `san_moves` differ in length is beyond me. Maybe the internal `_stack` array of `chess.Board()` should be used directly to feed the `history` array instead of calling `_board_state()`? I don't think the behavior is going to be any different, but it's worth a try.

**Comment by PedanticHacker** [comment]
Don't worry, the code regarding `history.pop()` works correctly. I've posted the exception traceback when the `san_moves` array wasn't implemented yet. Now I've updated my exception traceback. It is similar to yours.

**Comment by PedanticHacker** [comment]
Maybe we should `pop` from the `game.board._stack` as well? This array holds the `BoardState` objects. What do you think?

**Comment by mfitzp** [comment]
Yep @PedanticHacker, I actually just ended up using the Game.pop() method -- although this performs a restore for each pop, it means we're not using private _underscore methods. If there is a performance impact updating the engine for every step, you can switch out to...

```python
self.history.pop()
self.game._stack.pop()
self.san_moves.pop()
```

See the PR for a remaining issue, that prevents editing the first move.

**Comment by PedanticHacker** [comment]
As I've tested, after you select a move in the moves table (either by clicking on it, or scrolling to it using the scroll wheel), and you make a new move in that chessboard position, then select another move, notice that only the displayed arrow is correct for the move, but the actual chessboard position is one move behind. Why is that so?
