### ISSUE TITLE
Put added modules into a folder

### ISSUE THREAD

**Issue by PedanticHacker** [PedanticHacker/ChessFighter#5]
I don't know how to put the modules, I've just added to this repo, in a folder. Anyone knows?

**Comment by sshivaji** [comment]
Just move it to a folder and have a blank __init__.py file in that folder

**Comment by PedanticHacker** [comment]
Ah, thank you.

**Comment by sshivaji** [comment]
Shall I continue bringing back the old code into the new setup or did you want to make more cleanups?

**Comment by PedanticHacker** [comment]
Yes, please bring back the old code. But the old code is a mess. Too much unnecessary class overriding. We can surely avoid this. Also, the moves that are made on the chessboard can be acquired by doing
```
chessboard = chess.Board()
chessboard.push_san("e4")
chessboard.move_stack
[Move.from_uci('e2e4')]
```
and the moves made are in the move_stack list object which we can use to display each ply in a text read-only widget (which should not display the blinking cursor when clicked on).

So, I want to utilize as much of python-chess as possible. We don't need to do much manual hacking. ;)

**Comment by sshivaji** [comment]
You did not need init.py because all files are in same folder. If you want to reference a file in another folder, you need init.py.

**Comment by sshivaji** [comment]
Sure, I will attempt.

I will try to reuse python Chess code, but we need traditional recursive
PGN output, this is common in chess GUIs. Blinking cursor is easy to fix.

Some of the class overriding was needed as the default QT settings are not
optimal. However, I agree that overriding should only be done when
necessary.

**Comment by PedanticHacker** [comment]
Okay, let's do this.
