### ISSUE TITLE
Clicking outside the board still selects a piece

### ISSUE THREAD

**Issue by sshivaji** [PedanticHacker/ChessFighter#7]
When you refactored my code, this behavior is now broken. The svg object should connect to the mouse release event.

**Comment by PedanticHacker** [comment]
Hm, I didn't seem to test clicks outside the board. Can you fix this?

**Comment by sshivaji** [comment]
This is because pyQT5 somehow hardcodes the method "mousereleaseEvent" to trigger on QWidget action. On the coding and repos, I think its easier if we share one repo or maintain 2 different forks. Merging back and forth can be harder. Btw, I like your SVG work! I will patch this and send a pull request. After that we can figure out if sharing repo or maintaining 2 is better

**Comment by PedanticHacker** [comment]
Let's share the repo. What do you think?

**Comment by sshivaji** [comment]
Yes, can you share your repo. Go to https://github.com/sshivaji/ChessFighter/settings/collaboration and add me. This issue is fixed. I am going to add in database, pattern search, opening book support.

**Comment by sshivaji** [comment]
Thx, Just accepted your invite. My email is sshivaji@gmail.com. Whats the best way to chat, using gmail? I was planning to add more func from what I did before. What is your main interest list?

**Comment by PedanticHacker** [comment]
My e-mail address is bostjan.xperia@gmail.com. E-mail correspondence is
okay for me.

**Comment by sshivaji** [comment]
Thanks, will follow up by email, and will close issue as its resolved!
