### ISSUE TITLE
Elaborate on 3 lines of code in the codebase

### ISSUE THREAD

**Issue by PedanticHacker** [PedanticHacker/ChessFighter#9]
@mfitzp, I have trouble understanding 2 lines of code in the codebase. I would be very happy if you find the time and elaborate on the following 2 lines of code.

***

1. https://github.com/PedanticHacker/ChessFighter/blob/e7a1ce44fa3419aea696df9c4e244550cb5d2b70/source/window.py#L557

    I don't understand this particular line. I commented it out and I experienced a crash in the app. It's not acting as a flag (so it's not used as `if is_legal_move: ...`), it is just there as a local variable. How is it possible this line is so crucial? Can you elaborate on this?

***

2. https://github.com/PedanticHacker/ChessFighter/blob/e7a1ce44fa3419aea696df9c4e244550cb5d2b70/source/model.py#L33

    I would also like you to elaborate on why we need to catch that `IndexError`. I feel like this is some sort of a hack. I generally don't like hacks, being a pedantic hacker. :)  Is there any way we can implement this by not checking for an `IndexError`, so to make the code more clean?

    Um, writing this issue makes me realize something about this `IndexError` thing. Since the move stack is empty at the beginning of the game and accessing a move with the `converted_index` on an empty move stack is, indeed, an `IndexError`. I understand this much. But if I insert `print("IndexError was triggered!")` in that `except` block (before the `return` statement) to see when this `IndexError` gets triggered, I get a lot of those `IndexError was triggered!` printouts.

    So what is going on here?

**Comment by mfitzp** [comment]
1. Good question! Are you sure that was the cause of the crash? I've removed it here and see no effect -- looking at the code for the python-chess library, this call just returns `True` or `False` and doesn't appear to modify the board state (there are methods that push and then pop moves, but don't think this is one of them).

2. The tableview has 2 dimensions -- rows and columns -- which we return, depending on the size of the move structure. For a single row the number of rows is 1, and the number of columns is always 2. In the case where we have only 1 move, the 2nd column data is not there. When Qt tries to draw that cell, it calls the data method with that index, we calculate the index, and .... it doesn't exist.  That's the cause of the `IndexError`.

Catching exceptions you expect is the *correct* thing to do in Python (ask forgiveness, not permission) -- the bad thing, is catching broad exceptions, e.g. Exception -- which swallows up everything. You could do the following if you prefer though --

```python
        if converted_index > len(self._moves) - 1:
            return
```
You could tell Qt there is only a single column for the first data item, e.g. with 

```python
    def columnCount(self, model_index):
        """
        Returns the number of columns in the moves table which is
        always 2.
        """
        return 2 if len(self._moves) > 1 else 1
```

...but that will shown only 1 column header too... 

![singlecol](https://user-images.githubusercontent.com/126239/93804774-10071a80-fc47-11ea-9887-c0330f63f657.JPG)

**Comment by PedanticHacker** [comment]
1. Yeah, I must have done something else wrong and thought the line 557 was to blame. :)
2. And yeah, you're absolutely right! Thanks for elaborating on this.

***

And now for something completely different. :)

There's a 3rd thing I have a wish to understand. It's about
https://github.com/PedanticHacker/ChessFighter/blob/728731b7191ad77c7142cdb9dc2d91dc32bd7a3c/source/game.py#L97
I just don't understand why do we need to make the method `current_move_is_historic()` as a getter property of the `GameState` class in the `game` module. Can you elaborate on this also?
